version: "3.8"

services:
  db:
    container_name: pg-container
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    container_name: fmbconnect-api-container
    image: bmburhan/fmbconnect-api
    env_file:
      - .env
    ports:
      - 2000:2000
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data: